In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [5]:
#selecting data
#to select column
# Syntax : df["column_name"]

df["country"]
df[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [6]:
#to get data of row
df.loc[8195]
df.loc[0:2] # [start index : end Endex]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [7]:
df.iloc[0:2]  #exludeing end index

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [8]:
df.loc[0,"aqi"]

np.int64(108)

In [9]:
df.loc[0:2,["city","aqi"]]

       city  aqi
0  New York  108
1  New York   90
2  New York   84

In [10]:
#cell
df.at[0,"city"]
df.iat[0,2]

'New York'

In [12]:
df1 = pd.read_csv("loan_approval_data.csv")
df1.sample(10)

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
795,796.0,16060.0,8841.0,Self-employed,39.0,Married,3.0,640.0,4.0,NaN,19194.0,45530.0,7553.0,60.0,Business,Urban,Graduate,Male,NaN,No
882,883.0,5417.0,2496.0,Salaried,28.0,Married,2.0,731.0,0.0,0.18,6629.0,16672.0,10814.0,12.0,NaN,Rural,Not Graduate,Male,Private,Yes
963,964.0,8722.0,1638.0,Self-employed,47.0,Married,0.0,NaN,2.0,0.14,5644.0,36725.0,8253.0,72.0,Business,Urban,Not Graduate,NaN,Government,Yes
533,534.0,7320.0,4732.0,Self-employed,36.0,Married,3.0,625.0,0.0,0.48,3688.0,4656.0,38081.0,12.0,Personal,Semiurban,Graduate,Male,Private,No
604,605.0,10017.0,4293.0,Contract,NaN,Married,3.0,684.0,2.0,0.22,9554.0,21282.0,37355.0,12.0,Business,Urban,Graduate,Male,Business,Yes
101,102.0,14685.0,3004.0,Salaried,40.0,Single,2.0,777.0,1.0,0.50,14908.0,15202.0,22354.0,12.0,Car,Urban,Graduate,Male,Government,No
314,315.0,5051.0,2064.0,Contract,50.0,Single,1.0,756.0,2.0,NaN,11525.0,28878.0,28920.0,12.0,Personal,Semiurban,Graduate,Male,Business,NaN
672,673.0,15623.0,9829.0,Salaried,49.0,Married,2.0,683.0,1.0,0.42,4350.0,11419.0,18241.0,60.0,Home,Rural,Graduate,Female,Business,No
886,887.0,3854.0,7574.0,Salaried,40.0,Married,3.0,588.0,NaN,0.28,13311.0,13731.0,12218.0,24.0,Home,Urban,Not Graduate,Male,Government,No
905,906.0,15226.0,8264.0,Contract,23.0,Single,1.0,595.0,1.0,0.43,10057.0,47999.0,29000.0,72.0,Personal,Rural,Graduate,NaN,Government,No